name = "ponymon"
author = "SoniaSquishy & Shebang"
version = "rc-2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "564c05dbe1bc9a00d293a8d473b83f245ead3c7fa06b129752c5e27a96d135ad"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
