name = "Ponymon"
author = "SoniaSquishy & Shebang"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60cbc5e18ddea2342edce959ae0e951fc772752348b1e2a19c06dc06bfb0b1af"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
