name = "ponymon"
author = "SoniaSquishy & Shebang"
version = "rc-2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "167bc806fc9d42445ae63d4bc4fe08e1bbebdbf86d22b2915f2f76251c743d17"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
