name = "Ponymon"
author = "SoniaSquishy & Shebang"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26bb77b30cfc5e87cfe6a710729ec9cecf05101fe0b533750285687633d4513f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
