name = "ponymon"
author = "SoniaSquishy & Shebang"
version = "rc-2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee4c4b8f5b06f141fbf0e27cabcc3e2491e07adf5190e7a7d07d9a6bc0fc8b8d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
