name = "Ponymon"
author = "SoniaSquishy & Shebang"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17dec3916d3154690dd616a398da6ba4dfb284586a717cf9d93540404dc5e0bf"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
