name = "Ponymon"
author = "SoniaSquishy & Shebang"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92fc7a7a6618fbad4a6c6d3f75eff8e3b10881a9230d2fbd8a7c9419d2c91f1f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
