name = "ponymon"
author = "SoniaSquishy & Shebang"
version = "rc-2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c91902cc84f526696136afd8007993ec92f018b911b004679702c1af3d9faba9"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
