name: Publish .mrpack file
on:
  push:
    branches: [ main ]
    paths:
      - "index.toml"
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Trim Git SHA
        uses: priyesh2609/sha-trim-action@v1.1.1
      - name: Download and unzip packwiz
        run: | 
          curl -sSL https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip -o /tmp/packwiz.zip
          unzip /tmp/packwiz.zip -d ./
      - name: Produce .mrpack
        run: |
          chmod +x ./packwiz
          ./packwiz mr export -o ponymon-dev-${{ env.TRIMMED_SHA }}.mrpack
      - name: Upload Artifact
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: ./*.mrpack
