name: Publish .mrpack file
on:
  push:
    branches: [ main ]
    paths:
      - "index.toml"
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Trim Git SHA
        uses: priyesh2609/sha-trim-action@v1.1.1
      - name: Download and unzip packwiz
        run: | 
          curl -sSL https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip -o /tmp/packwiz.zip
          unzip /tmp/packwiz.zip -d ./
      - name: Produce .mrpack
        run: |
          chmod +x ./packwiz
          ./packwiz mr export -o ponymon-dev-${{ env.TRIMMED_SHA }}.mrpack
      - name: unzip the mrpack into a directory because github is really stupid
        run: |
          mkdir artifact
          unzip ponymon-dev-${{ env.TRIMMED_SHA }}.mrpack -d artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ponymon-dev-${{ env.TRIMMED_SHA }}.mrpack
          path: ./artifact
      - name: Test with itzg/minecraft-server
        run: |
          ls ${{ env.GITHUB_WORKSPACE}}
          docker run --rm -v ./:/gh -e MODRINTH_MODPACK=/gh/ponymon-dev-${{ env.TRIMMED_SHA }}.mrpack -e EULA=TRUE -e TYPE=MODRINTH --stop-timeout 300 itzg/minecraft-server
