name: Publish .mrpack file
on:
  push:
    branches: [ main ]
    paths:
      - "index.toml"
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Trim Git SHA
        uses: priyesh2609/sha-trim-action@v1.1.1
      - name: Download latest verison of Packwiz
        uses: actions/download-artifact@v4
        with:
          repository: packwiz/packwiz
          name: Linux 64-bit x86
          path: ./
          github-token: ${{ secrets.TOKEN}}
      - name: Unzip packwiz zip
        run: unzip 'Linux 64-bit x86.zip'
      - name: Produce .mrpack
        run: |
          chmod +x ./packwiz
          ./packwiz mr export -o ponymon-dev-${{ env.TRIMMED_SHA }}.mrpack
      - name: Upload Artifact
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: ./*.mrpack
